name = "textmint-backend-worker"
main = "src/index.ts"
compatibility_date = "2024-07-30"
node_compat = true
account_id = "7ab1a13a91644b84bf3f5f4b9d267b16"

[[d1_databases]]
binding = "DB"
database_name = "textmint-app-db"
database_id = "bb78c3a6-2429-43a0-8bc0-72090170a222"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "textmint"