name = "textmint-backend-worker"
main = "src/index.ts"
compatibility_date = "2024-07-30" # Use a recent compatibility date
node_compat = true

[[d1_databases]]
binding = "DB" # This is the name you'll use to reference D1 in your Worker code (e.g., env.DB)
database_name = "textmint-app-db"
database_id = "bb78c3a6-2429-43a0-8bc0-72090170a222" # Replace with your actual D1 Database ID


# R2 Bucket binding (this creates an R2Bucket object)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "textmint"